### ISSUE TITLE
can't download any other download link, or some tricks to clone this repo?

### ISSUE THREAD

**Issue by mmxuan18** [sercruzg/EgoDaily#1]

**Comment by sercruzg** [comment]
I have tested browser and git command downloads and they work just fine, do you have any more information i can look at? thank you

**Comment by mmxuan18** [comment]
this is my clone error, maybe this is good to store in google drive or dropbox.
git -c filter.lfs.smudge= -c filter.lfs.required=false --no-optional-locks -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree clone https://github.com/sercruzg/EgoDaily.git 
EgoDaily 
Cloning into 'EgoDaily'...
warning: templates not found in /usr/local/git/share/git-core/templates
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Completed with errors, see above

error even use download zip or ssh type clone

**Comment by sercruzg** [comment]
Hi, i just tried your command  without "--no-optional-locks" and was able to download it just fine, i will see if i can arrange another way you can download it

**Comment by sercruzg** [comment]
Hi, i moved all the images to google drive, you can use the link in the main page of the repository.

**Comment by mmxuan18** [comment]
thanks!!!
